# Site settings
title: Eugene's Blog
url: "http://thepry.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Asia/Makassar
description: >
  Web developer's blog

# Your information
email: ezvy@yandex.ru
author: Eugene Zviagintcev
avatar: "/assets/avatar.jpg"
profile: Web developer and digital nomad
twitter_username: the_pry
github_username:  thepry

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 10
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
